stages:
  - build
  - test
  - verify

build:
  stage: build
  script:
    - mvn compile
  tags:
    - linux

test:
  stage: test
  script:
    - mvn test
  tags:
    - linux

verify:
  stage: verify
  script:
    - mvn verify -DskipTests
  tags:
    - linux
